try:
    x = 1
except:
    print('error')


print(x)